// <auto-generated />
namespace solpr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class First : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(First));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:solpr/solpr/Migrations/202003260517195_First.Designer.cs
            get { return "202003260517195_First"; }
=======
            get { return "202003260414444_First"; }
>>>>>>> 4a55da9931de7feced28a7213cea22763b0c2f8c:solpr/solpr/Migrations/202003260414444_First.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
